### PR TITLE
Fix for #114.

### LINKED ISSUE #114: In stillshot mode, the image never actually updates after retrying
If you take a stillshot image, click retry, and take another, the preview will show the first image.

### PR DESCRIPTION
**Pull request by mowcixo**
This PR fixes #114 plus some code and layout cleanings and string hardcodings.

### CODE REVIEW

File: library/src/main/java/com/afollestad/materialcamera/internal/StillshotPreviewFragment.java [hunk 1]
```diff
@@ -60,23 +61,24 @@ public boolean onPreDraw() {
...
-//        if (mBitmap != null) {
-//            try {
-//                mBitmap.recycle();
-//            } catch (Throwable t) {
-//                t.printStackTrace();
-//            }
-//        }
-//    }
+    @Override
+    public void onDestroyView() {
```
Comment (afollestad) [inline library/src/main/java/com/afollestad/materialcamera/internal/StillshotPreviewFragment.java]: I actually commented this out because it causes issues when you rotate the device or switch rear/front facing, I believe.

**Comment by mowcixo** [comment]
Tested the new code rotating the device and switching rear/front facing. It works.
